<?php
use Magento\framework\View\Element\Template;
/** @var Template $block */
?>
<h1>the todo page </h1>
<ul>
    <li>One</li>
    <li>Two</li>
    <li>Three</li>
</ul>
<div data-bind="scope: 'todo'">
    <!-- ko template: getTemplate() --> <!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*":{
            "Magento_Ui/js/core/app": {
                "components": {
                    "todo": {
                        "component": "LotsofPixels_Todo/js/view/todo",
                        "template": "LotsofPixels_Todo/todo"
                    }
                }
            }
        }
    }
</script>